version: '3.9'
services:
  frontend:
    build:
      context: ./BusinessCardWeb.Client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./BusinessCardWeb.Server
      dockerfile: Dockerfile
    ports:
      - "32971:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
