version: '3.8'

services:
  frontend:
    build:
      context: ./businesscardweb.client
    ports:
      - "3000:80" # Host:Container
    networks:
      - app-network

  backend:
    build:
      context: ./BusinessCardWeb.Server
    ports:
      - "5001:5001"

    networks:
      - app-network

networks:
  app-network:
    driver: nat
