FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY BusinessCardWeb.Server/BusinessCardWeb.Server.csproj BusinessCardWeb.Server/
RUN dotnet restore BusinessCardWeb.Server/BusinessCardWeb.Server.csproj
COPY . .
WORKDIR /src/BusinessCardWeb.Server
RUN dotnet build -c Release -o /app/build
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

# 安裝必要的工具和 vsdbg
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl unzip && \
    curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

EXPOSE 5000
ENTRYPOINT ["dotnet", "BusinessCardWeb.Server.dll"]
