# 使用 Node 建構階段
FROM node:22.13.1 AS build

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# 使用 Nginx 提供靜態資源
FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
